---
title: "testing_raw_before_z"
author: "Sahar Fatima"
date: "10/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective
Testing whether muscle relaxation would be less if we calculated bin difference scores when the data is raw and then convert to z-scores. 

## Just going to test out responding to facial sitmuli 

### load packages 
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(formattable) # useful for controlling decimal places
library(here)
library(lme4)
library(lmerTest)
library(ggeffects)
library(broom.mixed)
library(pixiedust)
library(beepr)
library(effsize)
library(lsmeans)

options(scipen = 999) #set no scientific notation
```

### read in data
```{r}
faces <- read_csv(here("R_analysing", "data", "7_face_false.csv")) %>% # face data 
  select(-outlier1.5SD) %>%
   mutate(condition = recode(condition, "429" = "Angry","673" = "Happy", .default = "NA"))
```

### make data wide
```{r}
# Cheek First

# make face wide - only on cheek data
faces_cheek_wide <- faces %>%
  select(pp_no, condition, bin, trial, muscle, rms) %>%
  filter(muscle == "cheek") %>%
  pivot_wider(names_from = bin, 
              values_from = rms) %>%
  rename(BL = bin_0)

face_wide_cheekdiff <- faces_cheek_wide %>%
  mutate(diff_bin1 = bin_1 - BL, 
         diff_bin2 = bin_2 - BL,
         diff_bin3 = bin_3 - BL, 
         diff_bin4 = bin_4 - BL,
         diff_bin5 = bin_5 - BL, 
         diff_bin6 = bin_6 - BL,
         diff_bin7 = bin_7 - BL, 
         diff_bin8 = bin_8 - BL, 
         diff_bin9 = bin_9 - BL, 
         diff_bin10 = bin_10 - BL) %>%
  select(-BL, - starts_with("bin"))

face_cheeklong_diff <- face_wide_cheekdiff %>%
  pivot_longer(names_to = "bin", 
               values_to = "Zdiff", 
               diff_bin1:diff_bin10)

# Now Brow
faces_brow_wide <- faces %>%
  select(pp_no, condition, bin, trial, muscle, rms) %>%
  filter(muscle == "brow") %>%
  pivot_wider(names_from = bin, 
              values_from = rms) %>%
  rename(BL = bin_0)

face_wide_browdiff <- faces_brow_wide %>%
  mutate(diff_bin1 = bin_1 - BL, 
         diff_bin2 = bin_2 - BL,
         diff_bin3 = bin_3 - BL, 
         diff_bin4 = bin_4 - BL,
         diff_bin5 = bin_5 - BL, 
         diff_bin6 = bin_6 - BL,
         diff_bin7 = bin_7 - BL, 
         diff_bin8 = bin_8 - BL, 
         diff_bin9 = bin_9 - BL, 
         diff_bin10 = bin_10 - BL) %>%
  select(-BL, - starts_with("bin"))

face_browlong_diff <- face_wide_browdiff %>%
  pivot_longer(names_to = "bin", 
               values_to = "Zdiff", 
               diff_bin1:diff_bin10)

# combine cheek and brow
face_long_diff <- bind_rows(face_cheeklong_diff, face_browlong_diff)

# make wide 
faces_wide <- face_long_diff %>%
  pivot_wider(names_from = muscle, 
              values_from = Zdiff) %>%
  group_by(pp_no)

# transform to z-score
face_long_zscore <- faces_wide %>%
  mutate(Zcheek = scale(cheek, center = TRUE, scale = TRUE)) %>%
  mutate(Zbrow = scale(brow, center = TRUE, scale = TRUE)) %>%
  select(1:4, 7, 8)

# make long again
faces_zscore <- face_long_zscore %>%
  pivot_longer(names_to = "muscle", 
               values_to = "Zdiff", 
               5:6)


summary(faces_zscore)

```

## plotting - averaged across bin
```{r}

faces_zscore$condition <- as.factor(faces_zscore$condition)

faces_zscore %>%
  

       
```


### remove outliers
```{r}
face_out <- faces_zscore %>%
  group_by(pp_no, condition, trial, muscle) %>%
  mutate(meanZdiff = mean(Zdiff), sdZdiff = sd(Zdiff)) %>%
  mutate(bin_outlier = if_else(Zdiff > meanZdiff + 2*sdZdiff, "TRUE", "FALSE"))

# how many bins are outliers?
face_out$bin_outlier <- as.logical(face_out$bin_outlier)

face_outlier_true <- face_out %>%
  filter(bin_outlier == TRUE)

face_screen <- face_out %>%
  mutate(Zdiff = replace(Zdiff, bin_outlier == "TRUE", NA))

face_screen %>%
  group_by(condition, muscle) %>%
   summarise(meanZ = mean(Zdiff, na.rm = TRUE), 
            sd_RMS = sd(Zdiff, na.rm = TRUE), 
            n = n(), 
            stderr = sd_RMS/sqrt(n)) %>%
  ggplot(aes(x = muscle, y = meanZ, group = condition, fill = condition)) + 
  geom_bar(stat = "identity", 
           width = 0.9, 
           position = "dodge") + 
  scale_y_continuous(limits = c(-0.1, 0.1))

```

#### lmm analysis
```{r}
face_cheek_test <- face_screen %>%
  mutate(log_modulus = sign(Zdiff) * log(1+abs(Zdiff)))

lm_face_cheek_test <- lmer(log_modulus ~ condition + bin + condition*bin + (1 + condition|pp_no), data = face_cheek_test, REML = FALSE)

anova(lm_face_cheek_test)

summary(lm_face_cheek_test)
```

