---
title: "test_zscore"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(skimr)
library(naniar)
```

# read in data

```{r message=FALSE, warning=FALSE}
data <- read_csv(here::here("data", "adult_child_combined", "clean_no_bl_outliers.csv"))
```



- make data wide, use mutate to make new z variables 

```{r}
data_zscore <- data %>%
  pivot_wider(names_from = muscle, values_from = rms) %>%
  group_by(pp_no) %>%
  mutate(zbrow = scale(brow, center = TRUE, scale = TRUE)) %>%
  mutate(zcheek = scale(cheek, center = TRUE, scale = TRUE)) 


zbaseline <- data_zscore %>%
  group_by(pp_no) %>%
  filter(bin == "bin_0") %>%
    mutate(zbrow = scale(brow, center = TRUE, scale = TRUE)) %>%
  mutate(zcheek = scale(cheek, center = TRUE, scale = TRUE)) 
  
zbins <- data_zscore %>%
  group_by(pp_no) %>%
  filter(bin != "bin_0") %>%
  mutate(zbrow = scale(brow, center = TRUE, scale = TRUE)) %>%
  mutate(zcheek = scale(cheek, center = TRUE, scale = TRUE)) 

zbase_bins <- rbind(zbaseline, zbins) %>%
  arrange(pp_no, trial, bin)

zbase_bins %>%
  group_by(pp_no) %>%
  arrange(pp_no, model, trial, bin) %>%
  summary() 

```


















